server:
  port: 8085

spring:
  application:
    name: ICH-App
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{xxxxxx}/ichapp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: xxxxxxx
    password: xxxxxxx
  redis:
    host: localhost
    port: 6379
    password:
    connect-timeout: 10000

  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: /home/lighthouse/static/**

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


tencent:
  sms:
    keyId: xxxxxxxxxxxx #腾讯云keyId
    keySecret: xxxxxxxxxxxx #腾讯云keySecret
    smsSdkAppId: xxxxxxxxxxxx #腾讯云appId
    signName: 拾旧空间公众号
    templateIdLogin: 1539056
    templateIdRegister: 1539063
    smsClient: ap-nanjing
    url: sms.tencentcloudapi.com

img:
  filePath: /home/lighthouse/static/
