server:
  port: 8085

spring:
  application:
    name: ICH-App
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.143.162.177:3306/ichapp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: weibingrui1808.
  redis:
    host: localhost
    port: 6379
    password:
    connect-timeout: 10000

  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: /home/lighthouse/static/**

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


tencent:
  sms:
    keyId: AKIDykGXZLr78tOdMq31jBOL3VifMo1yf6IE
    keySecret: kniOozua0A5lR0OaYIo6Azc2EByYxA9x
    smsSdkAppId: 1400735487
    signName: 拾旧空间公众号
    templateIdLogin: 1539056
    templateIdRegister: 1539063
    smsClient: ap-nanjing
    url: sms.tencentcloudapi.com

img:
  filePath: C:\Users\韦秉芮\Desktop\推荐1\
#  filePath: /home/lighthouse/static/
